# Generated by Django 3.2.13 on 2022-05-22 14:17

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(max_length=12, validators=[accounts.validators.validate_company_id], verbose_name='사업자등록번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^010-?[1-9]\\d{3}-?\\d{4}$')], verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='웹 사이트 주소'),
        ),
    ]
