# Generated by Django 3.2.13 on 2022-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220522_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=20, verbose_name='회사명'),
        ),
    ]
