# Generated by Django 3.2.13 on 2022-05-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
