# Generated by Django 3.2.13 on 2022-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=50, verbose_name='회사 주소'),
        ),
    ]
