# Generated by Django 3.2.13 on 2022-05-22 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='qualification_license',
            field=models.CharField(blank=True, max_length=70, verbose_name='자격요건'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favor',
            field=models.CharField(max_length=70, verbose_name='우대사항'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)], verbose_name='제목'),
        ),
    ]
