# Generated by Django 3.2.13 on 2022-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20220523_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favor',
        ),
        migrations.AddField(
            model_name='post',
            name='employment',
            field=models.CharField(default='-', max_length=70, verbose_name='고용형태'),
        ),
        migrations.AddField(
            model_name='post',
            name='recruiter',
            field=models.CharField(default='-', max_length=50, verbose_name='담당자명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='call_number',
            field=models.CharField(default='-', max_length=13, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='-', verbose_name='특이사항'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gather_count',
            field=models.CharField(max_length=50, verbose_name='모집인원'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=50, verbose_name='근무지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay',
            field=models.CharField(default='-', max_length=50, verbose_name='임금'),
        ),
        migrations.AlterField(
            model_name='post',
            name='qualification_license',
            field=models.CharField(default='-', max_length=70, verbose_name='자격사항'),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_time',
            field=models.CharField(default='-', max_length=50, verbose_name='근무시간'),
        ),
    ]
