# Generated by Django 3.2.13 on 2022-05-22 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='call_number',
            field=models.CharField(max_length=13, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=10, verbose_name='모집분야'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='favor',
            field=models.CharField(max_length=50, verbose_name='우대사항'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gather_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='모집인원'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=50, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pay',
            field=models.CharField(max_length=50, verbose_name='급여액'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)], verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_time',
            field=models.CharField(max_length=50, verbose_name='근무시간'),
        ),
    ]
